### ISSUE TITLE
Disallow multi-coach session creation "save" button for single session

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#10]
If someone accidently presses multi-coach session creation, it does not look different from a normal one.  In theory, they should not be using it for a single session.  So the save button could be disabled until the plus is clicked for a second session.

**Comment by bonejon** [comment]
Actually, this doesn't work. if a single session has been created and we want to convert it into a multi-session of 2 then we need to create a multi-session with a single session first to drop the other session into.
