### ISSUE TITLE
More information fields

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#11]
Recently I tried to put a URL for the route into the description.  Beside being user unfriendly (not being a link so had to be cut and pasted) it did not wrap around in its cell, so pushed the right hand column off my mobile phone. Yes I could scroll to find it.
So, perhaps that could be an optional field that accesses the URL when clicked.

Also, session leads are forgetting to add whether we need a) high vis, b) head torch, c) trail shoes, d) the pace.

You could make some of these fields requiring the session lead to tick one of "not needed", "helpful", "mandatory" for high vis and head torch and trail shoes, with nice symbols appearing when they do. I had to be asked about my trail run today!

You could make pace mandatory, but allow text (or easy pull up favourites of 9.00 to 9:30, 8.30 to 9.00 etc, even "recovery" etc.

This would get better consistency and completeness of information across all leaders.

**Comment by bonejon** [comment]
I will look at links seperately.

Changes have been made to allow the club to define tags and then assign them to a session, these tags will be displayed within the sessions to make it easier for members understand run type and pace. 


![Screenshot 2021-01-23 at 12 30 44](https://user-images.githubusercontent.com/11681476/105578303-0289aa80-5d77-11eb-8c1e-21e144e42feb.png)
![Screenshot 2021-01-23 at 12 31 09](https://user-images.githubusercontent.com/11681476/105578306-04ec0480-5d77-11eb-853e-031966bc0cf7.png)
![Screenshot 2021-01-23 at 12 31 19](https://user-images.githubusercontent.com/11681476/105578308-06b5c800-5d77-11eb-9942-1ea8480b4d48.png)
