### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#12]
Although the app is intuitive mostly, there are a few helpful training points that could be made.  An extra "help" or "tips" tab might be useful giving members help (and sessions leads further help) (just for them).  You can then ask members to look at it.  Yes, I know many wont!  e,g,

Members
- If a session is full and you are dissapointed, reserve a place since the club then knows to see if it can put on another session.
- If you cannot make a session, please unregister in good time as it will often deny someone else their training.
- If there is not room, keep checking as usually someone will cancel on the last day.

Session leads
- Always post on Facebook first giving the URL "https://www.session-registration.club/club-sessions".  Some have not had the last bit, which can be confusing the first time as it goes to their home page.
- If sessions leads know they are putting on parallel sessions, one of them should create a multi-coach session, letting the individual coaches fill out their specific details.
- Allow a senior coach to publish on facebook and create a multi-coach session first.
- Always state the time the session will actually start, not adding in buffer time, e.g. 07:00, not 06:50, for consistency.
- Remember to state need for hi vid, head torch, trail shoes etc where necessary.  State the pace and whether tarmac or trail.
- Don't forget to tick all those who are joining you and then press "start" to enter them onto the Covid register

**Comment by bonejon** [comment]
I'll close this in favour of the help text just added
