### ISSUE TITLE
Merge into multi-session

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#15]
Either run leaders forget to create multi-sessions or they just do not know others are about to create single session on the same night.  It would be good if after seeing multiple single session if they could combine two or more into one multi-session.

Similarly, if one accidently creates a multi-session for a single session, rather than delete and start again, it might be nice to be able to convert it, or possibly a single multi-session is make to look just like a single session.

In fact, one could make all single session to be single multi-sessions, but look like single sessions so the next one could add to it.

Of course multiple single multi-sessions that have been converted into a multiple multi-sessions could be.....!

**Comment by bonejon** [comment]
Be interesting to see how this works in practice..

I've added drag / drop to the session list screen. You can now drag a single session into a multi-part session on the same day. Once it's in though, thats it you can't drag it back out.
