### ISSUE TITLE
Delete Session

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#16]
Matthew bailed out of his session to join another tonight, but could not delete it or set the members to 0 to stop others joining.  Could there be a way to not necessarily delete it, but make it disappear from the riff-raff view?

**Comment by bonejon** [comment]
Added and now available in the dev site for testing.

To delete a multi-part session you must first delete all the child sessions and then can delete the parent session. There are no notifications so it will be the coaches responsibility to contact any members registered to the session.
