### ISSUE TITLE
Membership approval notice

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#17]
When someone registers for the first time on the web, it says "your membership of CPRC has not yet been approved".  However their "membership of CPRC" has been approved as they are on facebook"  This may confuse.  Suggest you say "Registration of the CPRC app has not yet been approved".

Also Laura has issued with the app (not sure which one) but no issues with the web.

**Comment by bonejon** [comment]
Message changed to -->

Access to the CPRC session registration app has not yet been approved. When your membership has been approved you will see the session booking screens.

**Comment by bonejon** [comment]
Actually, will change the "membership" in the second sentence to "access"
