### ISSUE TITLE
Poor Landscape screen use

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#2]
![Screenshot_20200929-215321_Chrome](https://user-images.githubusercontent.com/72106312/94614800-a61def00-029e-11eb-97f6-5ceffd15e4cf.jpg)
The active scrolling area of screen in landscape mode for the home page is vertically too small, with too much background showing.  Image attached from Android s9 phone.

**Comment by bonejon** [comment]
I'll look at this, I have an idea on how to change the layout to make it fit landscape mode.

**Comment by bonejon** [comment]
This should be a bit better now. Anything other than a desktop browser should have narrow margins and in certain screen sizes the email address and icon are replaced with Profile for better real estate usage.
