### ISSUE TITLE
Minor issue with disappearing text

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#5]
![Screenshot_20201004-214506_Chrome](https://user-images.githubusercontent.com/72106312/95027077-b8789e00-068d-11eb-830b-5199f27668f6.jpg)
![Screenshot_20201004-214506_Chrome](https://user-images.githubusercontent.com/72106312/95027145-3f2d7b00-068e-11eb-971f-0c0f447a6a86.jpg)

In portrait mode on my mobile phone, the number on the reserve list is hidden by the unregister button.  See attached screen shot(s!).

**Comment by bonejon** [comment]
New layout should have resolved this issue now
