### ISSUE TITLE
Access for session leads to see all runners in all groups

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#7]
When there are say 6 related sessions, I only see names of those in my session.  When discussing who should go where, it would be helpful and educational for run leaders to see who attends which group.  Just needs a “view” button for session leads to see for all sessions.

**Comment by bonejon** [comment]
Sessions now have an expanding section for the "Places available" label, when expanded shows the members registered for the session (reserve) will be added if the member is on the reserve list.
This list is available to all members.

![Screenshot 2021-01-23 at 12 24 53](https://user-images.githubusercontent.com/11681476/105578200-50ea7980-5d76-11eb-941c-4d25dbda75d4.png)
